name: Node.js Package

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com/
          scope: '@gdominguez210'
      - run: pnpm install
      - run: pnpm add -D @semantic-release/changelog @semantic-release/git
      - run: pnpm run build:lib
      - run: pnpm dlx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
